# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - kinova_joint_1
      - kinova_joint_2
      - kinova_joint_3
      - kinova_joint_4
      - kinova_joint_5
      - kinova_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - kinova_right_finger_bottom_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity